name: Linux CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
          # git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
          git submodule update --init

      - name: Setup
        run: |
          mkdir -p ~/.ssh/
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          sudo apt-get update
          sudo apt-get install -y git cmake protobuf-compiler libsodium-dev libgflags-dev libprotobuf-dev libutempter-dev g++

      - name: Test with ubsan
        run: |
          mkdir build
          cd build
          cmake -DSANITIZE_UNDEFINED=ON ../
          make -j`nproc`
          pushd build
          ./et-test
          popd
          rm -Rf build

      - name: Test with asan
        run: |
          mkdir build
          cd build
          cmake -DSANITIZE_ADDRESS=ON ../
          make -j`nproc`
          pushd build
          ./et-test
          popd
          rm -Rf build

      - name: Test with msan
        run: |
          mkdir build
          cd build
          cmake -DSANITIZE_MEMORY=ON ../
          make -j`nproc`
          pushd build
          ./et-test
          popd
          rm -Rf build

      - name: Test with tsan
        run: |
          mkdir build
          cd build
          cmake -DSANITIZE_THREAD=ON ../
          make -j`nproc`
          pushd build
          ./et-test
          popd
          rm -Rf build
