name: Linux CI

on:
  push:
  pull_request:

jobs:
  ubsan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
          git submodule update --init
          mkdir -p ~/.ssh/
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          sudo apt-get update
          sudo apt-get install -y git cmake gdb protobuf-compiler libsodium-dev libgflags-dev libprotobuf-dev libutempter-dev g++

      - name: Test with ubsan
        run: |
          mkdir build
          pushd build
          cmake -DSANITIZE_UNDEFINED=ON ../
          make -j`nproc`
          gdb -batch -ex "run" -ex "bt" --args ./et-test
          popd
          rm -Rf build

  asan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
          git submodule update --init
          mkdir -p ~/.ssh/
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          sudo apt-get update
          sudo apt-get install -y git cmake gdb protobuf-compiler libsodium-dev libgflags-dev libprotobuf-dev libutempter-dev g++

      - name: Test with asan
        run: |
          mkdir build
          pushd build
          cmake -DSANITIZE_ADDRESS=ON ../
          make -j`nproc`
          gdb -batch -ex "run" -ex "bt" --args ./et-test
          popd
          rm -Rf build

  msan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
          git submodule update --init
          mkdir -p ~/.ssh/
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          sudo apt-get update
          sudo apt-get install -y git cmake gdb protobuf-compiler libsodium-dev libgflags-dev libprotobuf-dev libutempter-dev g++
          sudo apt-get upgrade

      - name: Test with msan
        run: |
          mkdir build
          pushd build
          cmake -DSANITIZE_MEMORY=ON ../
          make -j`nproc`
          gdb -batch -ex "run" -ex "bt" --args ./et-test
          popd
          rm -Rf build

  tsan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
          git submodule update --init
          mkdir -p ~/.ssh/
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          sudo apt-get update
          sudo apt-get install -y git cmake gdb protobuf-compiler libsodium-dev libgflags-dev libprotobuf-dev libutempter-dev g++

      - name: Test with tsan
        run: |
          mkdir build
          pushd build
          cmake -DSANITIZE_THREAD=ON ../
          make -j`nproc`
          gdb -batch -ex "run" -ex "bt" --args ./et-test
          popd
          rm -Rf build
