name: Linux CI

on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
          git submodule update --init
          mkdir -p ~/.ssh/
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          sudo apt-get update
          sudo apt-get install -y git cmake protobuf-compiler libsodium-dev libgflags-dev libprotobuf-dev libutempter-dev g++

  ubsan:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Test with ubsan
        run: |
          mkdir build
          cd build
          cmake -DSANITIZE_UNDEFINED=ON ../
          make -j`nproc`
          ./et-test
          popd
          rm -Rf build

  asan:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Test with asan
        run: |
          mkdir build
          cd build
          cmake -DSANITIZE_ADDRESS=ON ../
          make -j`nproc`
          ./et-test
          popd
          rm -Rf build

  msan:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Test with msan
        run: |
          mkdir build
          cd build
          cmake -DSANITIZE_MEMORY=ON ../
          make -j`nproc`
          ./et-test
          popd
          rm -Rf build

  tsan:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Test with tsan
        run: |
          mkdir build
          cd build
          cmake -DSANITIZE_THREAD=ON ../
          make -j`nproc`
          ./et-test
          popd
          rm -Rf build
